### ISSUE TITLE
Riječnici

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#1]
Joža,
napravio sam neke izmjene na riječnicima za Nissan, ali i sve ostale marke (usput). No to se ne vidi:
- https://rs.nv.nissan.sto2.hr/Nissan-Novi-Qashqai-NConnecta-13-DIGT-158-Mild-Hybrid/16625/request-offer
npr: Fizičko lice, ne Fizička osoba, ovlašćene ne ovlatene i sl.
- https://izaberiiodvezi.nissan.rs/Forms/16349 - ne vidi se niti tu. No to si rekao da ti moraš još nešto pushati...
- e sad, jel' bi se te izmjene i tu trebale vidjeti: https://izaberiiodvezi.renault.rs/Forms/15683?

**Comment by jzlimen** [comment]
Riješeno
