### ISSUE TITLE
RKS riječnik

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#12]
Joža,
pushao sam upravo sad rks.js riječnik na forme. Možeš li napraviti ono šta trebaš da se "vidi" vani?

Također, prije nego sam ovo radio, primjetio sam da ne radi forma za onaj auto koji si ti bio unio: https://certified.automita.com/Forms/1

![image](https://user-images.githubusercontent.com/72204614/171484825-eb94e8c9-1173-4336-b526-f5bf20f9a63c.png)

**Comment by sasadj1** [comment]
Pushao sam sad još jednom CG riječnik... Danas su poslali neke ispravke + Ante je sad unio...

**Comment by jzlimen** [comment]
Riješeno
