### ISSUE TITLE
[Nissan][hr, si, rs] Zamjena disclaimera

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#15]
Joža,
ja sam promijenio email adrese za Nissan forme u disclaimeru. Možeš li to pushati? Znam da si rekao da nemogu ja...

Tnx,
Saša.

**Comment by sasadj1** [comment]
Joža,
ovo možeš odraditi. Zamijenio sam sve šta sam trebao. Doći će u nekom trenu novi disclaimer za Hrv ali neznam kad :(

**Comment by sasadj1** [comment]
Joža,
ovo možeš napokon pushati u produkciju :)

Tnx,
Saša.

**Comment by jzlimen** [comment]
Riješeno
