### ISSUE TITLE
Update HR forme

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#17]
Joža,
zamijenio sam naziv tvrtke Renault Nissan Hrvatska u GA Croatia na online formama. To su nam tek nedavno poslali da smijemo napraviti. Pa daj pls. napravi push tih formi u produkciju.

Hvala!

**Comment by jzlimen** [comment]
Riješeno.

**Comment by sasadj1** [comment]
Eh... Na Nissanu ne radi?
https://izaberiiodvezi.nissan.hr/Nissan-Micra-NDesign-10-IGT-92/54613/request-offer

![image](https://user-images.githubusercontent.com/72204614/200426392-7da3ce23-5172-41b1-ae1c-b3a884b99154.png)
vs.
![image](https://user-images.githubusercontent.com/72204614/200426440-f9fed48c-682e-4404-9793-75fad9eeb546.png)

**Comment by sasadj1** [comment]
Btw. na Rabljena vozila Nissan radi: https://rabljenavozila.nissan.hr/Forms/55030

![image](https://user-images.githubusercontent.com/72204614/200426742-f5bc8e90-73e4-45d8-908c-86490ecf4b93.png)

Bit će da to moram negdje drugdje zamijeniti :(

**Comment by jzlimen** [comment]
Riješeno
