### ISSUE TITLE
Promjena u riječniku

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#2]
Joža,
napravio sam promjenu u Slovenskom riječniku za forme:
![image](https://user-images.githubusercontent.com/72204614/145630972-3df67d33-90e1-49fa-ba74-c481a14b0760.png)
![image](https://user-images.githubusercontent.com/72204614/145630999-2854b311-975a-425d-8078-bd130b9429c6.png)

Stavio sam to na git ali u produkciji se to još ne vidi: https://izberiinodpelji.renault.si/Forms/306363

![image](https://user-images.githubusercontent.com/72204614/145631219-bac82d4c-adc3-4245-8f77-3c9e15ae0408.png)

Nisam ništa mergaeo na gitu jer mi se čini da netreba, da je to odmah pushano na produkciju...

**Comment by jzlimen** [comment]
Riješeno
