### ISSUE TITLE
Fotografija vozila

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#20]
Joža,
daj vidi pls. ovo: https://rabljenavozila.renault.hr/Forms/69535. Slika je u biti obična, a trebala bi biti sa onim nazivom Renault Selection (https://rabljenavozila.renault.hr/Vozila/Renault-Clio-Blue-dCi-85-Zen/69535/?q=MXxzb3J0X2NpamVuYXwwfDF8MTUxNXwwfDB8MHwwfDB8MHwwfHx8fA==).

Tnx,
Saša

**Comment by jzlimen** [comment]
Riješeno
