### ISSUE TITLE
[hr, slo, rs] Nissan online forme - Izaberi i odvezi

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#21]
Grga,
Nissan se nešto zalio da im je button na formi "jadan": https://izaberiiodvezi.nissan.hr/Nissan-Juke-Tekna-10-DIGT-114/59689/request-offer
![image](https://github.com/wssto2/rna-contact-form/assets/72204614/6521cb03-9414-4f13-ab7b-8a9855baced2)

Mateja je rekla da Nissan ima neke nove standarde (zaobljeni crni buttoni) no vidjeli smo na nekoj FR formi da je taj button za submit po cijeloj sirini tog diva:
![image](https://github.com/wssto2/rna-contact-form/assets/72204614/a7388526-d38b-4cc0-9c40-060d773c1f57)

Evo neki primjer: https://www.nissan.fr/essai-en-concession.html

Helena je rekla da možemo slobodno to tako napraviti.

Tnx,
Saša

**Comment by gborac** [comment]
@sasadj1 evo riješeno
https://izaberiiodvezi.nissan.hr/Nissan-Juke-NConnecta-10-DIGT-114/69858/request-offer
https://rabljenavozila.nissan.hr/Forms/69117
