### ISSUE TITLE
Šta se poziva za odraditi formu

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#23]
Jole,
možeš li mi pls. popisati koju moju skriptu pozivaš vezano za forme sa stranica:
- https://izaberiiodvezi.renault.hr/Forms/81283
- https://izberiinodpelji.renault.si/Forms/467528
- https://izaberiiodvezi.renault.me/Forms/755
- https://certified.automita.com/Forms/112
- https://koristenivozila.renault.mk/

Netko je nešto "drkao" u kodu pa imamo neke fileove za koje neznam ćemu služe: send_uk5a8dj_gdpr-v5.php

Hvala ti puno,
poz,
Saša

**Comment by jzlimen** [comment]
Hrvatska i Slovenija imaju V5, ostale države imaju V4, no obje verzije forme rade submit podataka na isti URL:
```js
this.arvUrl() + 'forms/send-gdpr/rabljena_vozila/' + this.country + '/';
```

**Comment by sasadj1** [comment]
Super. U htaccessu u svim zemljama je za to ovo:
`RewriteRule ^send-gdpr/([0-9a-zA-Z.,_\-]+)/([0-9a-zA-Z.,_\-]+)/ send_uk5a8dj_gdpr-2023.php?w=$1&ln=$2 [NC]`

To znači da se uzima ova skripta: send_uk5a8dj_gdpr-2023.php. Generalno me jebe ovo u htaccess fileu:
```
# Nova V5 forma - 11.7.2023
RewriteRule ^send-gdpr-v5/([0-9a-zA-Z.,_\-]+)/([0-9a-zA-Z.,_\-]+)/ send_uk5a8dj_gdpr-v5.php?w=$1&ln=$2 [NC]

```
Nemam pojma tko je to stavio i zašto...

Šta misliš, da nas ne buni, da iskomentiram tu zadnju liniju? Mislim na ovo: "send-gdpr-v5"?
