### ISSUE TITLE
Kriva adresa na formi

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#24]
Joža,
ovo sam danas primjetio. Ovo [vozilo](https://rabljenavozila.renault.hr/Vozila/Renault-Kangoo-Express-1.5-DCI-75/67927/?q=MXxzb3J0X2NpamVuYXwwfDB8MHwzMjEwMHwwfDB8MHwwfDB8MHx8fHw=) se nalazi na lokaciji Vinkovci. 
![image](https://github.com/wssto2/rna-contact-form/assets/72204614/67e761c0-2ebb-48c8-b539-c6b98f30d77b)

Kad se ode na [formu](https://rabljenavozila.renault.hr/Forms/67927) ispisana je glavna adresa koncesije (tablica koncesionari). Trebalo bi ispisati adresu lokacije, tj. iz tablice: koncesionari_lokacije.
![image](https://github.com/wssto2/rna-contact-form/assets/72204614/d20fe385-7cec-4483-8623-78587b82bb55)

Vidi hoće li možda Grga to riješiti.

Tnx,
Saša

**Comment by jzlimen** [comment]
<img width="682" alt="image" src="https://github.com/wssto2/rna-contact-form/assets/16623112/3686ce7c-65ea-484e-8944-ae9df0052666">

Riješeno
