### ISSUE TITLE
DWS lead forme

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#3]
Joža,

daj kad stigneš napravi da se lead forme za dealere vuku isto iz onih novih... Jer nam se još uvijek vuku sa ARV-a. Pričali smo o tome, rekao si da imaš ideju kako to riješiti...

Btw. neznam koliko ti treba vremena za ovo. Naime imamo neke greške na tim formama i sad mi bzvz. da @antesto2 to rješava ako ćemo riješiti na ovaj način...

Tnx,
Saša.

**Comment by jzlimen** [comment]
Koliko vidim ovo je riješeno.
