### ISSUE TITLE
Razbila se malo forma

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#4]
@antesto2 , Joža,
nisam siguran kad se desilo, ali pretpostavljam nakon šta ste objavili novi header / footer.
https://izaberiiodvezi.nissan.hr/Nissan-Micra-NSport-10-IGT-92/49691/request-offer
![image](https://user-images.githubusercontent.com/72204614/154317994-97482553-6f61-4672-bd03-1c0bc59ccf5e.png)

Brijem da je ovako izgledala prije: https://kupnja.nissan.hr/?modelCode=F16

**Comment by jzlimen** [comment]
Riješeno
