### ISSUE TITLE
Forme - riječnici

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rna-contact-form#5]
Joža,
samo da ne zaboravimo. Pls. objavi izmjene na riječnicima za ba i me šta sam napravio... I samo sitnica, pišem da se sjetimo. CG riječnik ima samo: legal_disclaimer_content_renault, dok ba riječnik ima: legal_disclaimer_content_renault + legal_disclaimer_content_dacia + legal_disclaimer_content_nissan.

Tnx,
Saša.

**Comment by sasadj1** [comment]
Da onaj "izgubljeni" komentar je trebao ići tu:
"Ipak me ne radi dobro, nema pravne napomene na Dacii i Nissanu. pa sam ponovno stavio me riječnik. Pls. napravi šta trebaš kad ćeš moći. Ponedjeljak je ok jer im neću prije slati mail!!!"

**Comment by sasadj1** [comment]
Joža,
daj pls. samo pushaj forme online... Tnx!

**Comment by jzlimen** [comment]
Riješeno

**Comment by sasadj1** [comment]
Ovo sam sad provjerio i sad je to ok: https://izaberiiodvezi.nissan.me/Forms-v4/543
![image](https://user-images.githubusercontent.com/72204614/167498862-4a10a217-70c5-4823-80a3-7f4df93576c7.png)
