### ISSUE TITLE
Update base.css

### ISSUE THREAD

**Issue by antesto2** [wssto2/rna-contact-form#9]
Bok Josipe,

Updateo sam css za formu da kod gdpr-a nemamo sive linkove nego da budu u istoj boji kao i tekst (jer je vecinom tako na sluzbenima), pa bi samo trebalo povuc promjene 

Hvala
Ante

**Comment by jzlimen** [comment]
Riješeno

**Comment by antesto2** [comment]
Oprosti na gnjavaži, ostala mi je jedna sitnica pa ako mozes jos jednom povuci

Hvala i oprosti na gnjavazi
Ante

**Comment by jzlimen** [comment]
Riješeno
